APP_NAME = "PromptMeld"
TAGLINE = "Write well and prosper"
APP_ID = "PromptMeld"
DEFAULT_PROJECT_NAME = "PromptMeld"
DATA_DIRECTORY_NAME = "PromptMeld"
LOG_FILE_NAME = "promptmeld.log"
MAIN_EXECUTABLE_NAME = "PromptMeld.exe"
AUTOMATION_EXECUTABLE_NAME = "PromptMeldAutomation.exe"
HOTKEY_RECEIVER_TITLE = "PromptMeldHotkeyReceiver"
SINGLE_INSTANCE_NAME = r"Local\PromptMeld-v1"

LEGACY_APP_NAME = "Writing Launcher"
LEGACY_APP_ID = "WritingLauncher"
LEGACY_DATA_DIRECTORY_NAME = "WritingLauncher"
LEGACY_HOTKEY_RECEIVER_TITLE = "WritingLauncherHotkeyReceiver"
LEGACY_SINGLE_INSTANCE_NAME = r"Local\WritingLauncher-v1"
LEGACY_STARTUP_LINK_NAME = "Writing Launcher.lnk"
